apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name:
build:
  local:
    push: false
  artifacts:
    - image: iyas/auth
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
